# This is a basic workflow to help you get started with Actions

name: CI/CD pipeline
on:
  push:

jobs:
 Docker-build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: firoj0786/app:latest


 Test-deploy:
    name: Test-Deploy

    runs-on: ubuntu-latest
    if: contains('refs/heads/develop',github.ref)

    permissions:
      deployments: write

    steps:
      - uses: actions/checkout@v1

      - uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment
        id: deployment
        with:
          token: '${{ github.token }}'
          environment-url: http://my-app-test.com
          environment: test

prod-deploy:
    name: prod-Deploy

    runs-on: ubuntu-latest
    if: contains('refs/heads/develop',github.ref)

    permissions:
      deployments: write

    steps:
      - uses: actions/checkout@v1

      - uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment
        id: deployment
        with:
          token: '${{ github.token }}'
          environment-url: http://my-app-prod.com
          environment: prod
