# This is a basic workflow to help you get started with Actions

name: CI/CD pipeline
on:
  push:

jobs:
 Docker-build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: firoj0786/app:latest


 Test-deploy:
    name: Test-Deploy

    runs-on: ubuntu-latest
    #if: contains('refs/heads/develop',github.ref)
    if: github.ref == 'refs/heads/develop'
    steps:
         - uses: actions/checkout@v2
         - name: Kubernets set context
           uses: azure/k8s-set-context@v2
           with:
              method: kubeconfig
              kubeconfig: ${{ secrets.KUBE_CONFIG }}

         - name: deploy
           run: |
              ls
              helm upgrade hello-world hello-world

 prod-deploy:
    name: prod-Deploy

    runs-on: ubuntu-latest
    #if: contains('refs/heads/develop',github.ref)
    if: github.ref == 'refs/heads/develop'
    steps:
        - uses: actions/checkout@v2
        - name: Kubernets set context
          uses: azure/k8s-set-context@v2
          with:
             method: kubeconfig
             kubeconfig: ${{ secrets.KUBE_CONFIG }}

        - name: deploy
          run: |
             ls
             helm upgrade hello-world hello-world
